"""Conservative pixel-evidence fusion of equal- and raw-heavy robust runs.

Both input CSVs must have been generated by this package from the same image
split. The selected demo reference CSV is never read here. Training labels are
used only for post-inference evaluation, never for choosing patch decisions.
"""
from __future__ import annotations

import argparse
import ast
import json
from pathlib import Path

import numpy as np

from . import robust_engine as engine
from .data import discover_scenes, read_gray, read_rows, write_rows
from .metrics import score_scene
from .robust_runner import validate_robust_predictions


RAW_WEIGHTS = {"raw": 1.5, "bp": 1.0, "hp": 0.5}


def _point(value: str):
    return None if value == "-1" else ast.literal_eval(value)


def _site(F: np.ndarray, point: tuple[int, int, int] | None):
    """Return rank and NCC at a predicted site; None if absent from shortlist."""
    if point is None:
        return None
    distance = np.hypot(F[:, 1] - point[0], F[:, 2] - point[1])
    rank = int(distance.argmin())
    return (rank, float(F[rank, 0])) if distance[rank] <= 12 else None


def _ring(image_hp: np.ndarray, patch_hp: np.ndarray, F: np.ndarray, rank: int) -> float:
    match = F[rank]
    return engine.ann_score(image_hp, patch_hp, match[1], match[2], -match[3], match[4])


def fuse_row(base: dict[str, str], raw: dict[str, str], equal_ev: dict,
             raw_ev: dict, image: np.ndarray, patches: list[np.ndarray]) -> tuple[dict[str, str], list[dict]]:
    """Fuse one scene using only image-derived match and annular evidence."""
    if base["Id"] != raw["Id"] or base["constellation"] != raw["constellation"]:
        raise ValueError("Input predictions disagree on scene ID or constellation name")
    count = int(base["n_patches"])
    if count != int(raw["n_patches"]) or len(patches) != count:
        raise ValueError("Input predictions disagree on patch count")
    output = dict(base)
    changed: list[dict] = []
    image_hp = None
    patch_hp: dict[int, np.ndarray] = {}

    def ring(index: int, F: np.ndarray, rank: int) -> float:
        nonlocal image_hp
        if image_hp is None:
            image_hp = engine.hp_pre(image)
        if index not in patch_hp:
            patch_hp[index] = engine.hp_pre(patches[index])
        return _ring(image_hp, patch_hp[index], F, rank)

    def field(index: int) -> str:
        return f"patch_{index + 1:02d}"

    # A geometry-only claim at the fourth-or-worse patch location must also
    # retain high-frequency ring detail. Otherwise abstain; do not guess a
    # different pixel location from the same ambiguous shortlist.
    for i in range(count):
        key = field(i)
        current, alternative = _point(output[key]), _point(raw[key])
        if current is None or alternative is not None or current[2] != 1:
            continue
        F = equal_ev["pf"][i]["F"]
        site = _site(F, current)
        if site is None or site[0] < 3:
            continue
        if ring(i, F, site[0]) >= 0.5:
            continue
        output[key] = "-1"
        changed.append({"patch": key, "action": "abstain_weak_geometry", "old": base[key],
                        "new": "-1"})

    # Accept a raw-heavy-only figure star only with strong independent ring
    # support. If another patch owns that star, compare both under the same
    # raw-heavy scoring weights and transfer ownership only on a clear win.
    offers = []
    for i in range(count):
        key = field(i)
        proposed = _point(raw[key])
        if _point(base[key]) is not None or proposed is None or proposed[2] != 1:
            continue
        F = raw_ev["pf"][i]["F"]
        site = _site(F, proposed)
        if site is None or site[0] > 2 or site[1] < 0.85:
            continue
        ann = ring(i, F, site[0])
        if ann >= 0.5:
            offers.append((site[1], i, proposed, ann))
    for score, i, proposed, ann in sorted(offers, reverse=True):
        key = field(i)
        owners = [(j, _point(output[field(j)])) for j in range(count) if j != i]
        owners = [(j, site) for j, site in owners if site is not None and
                  np.hypot(site[0] - proposed[0], site[1] - proposed[1]) <= 12]
        if not owners:
            output[key] = raw[key]
            changed.append({"patch": key, "action": "add_strong_figure", "old": base[key],
                            "new": raw[key]})
            continue
        if len(owners) != 1 or owners[0][1][2] != 1:
            continue
        incumbent_index, incumbent = owners[0]
        incumbent_F = raw_ev["pf"][incumbent_index]["F"]
        incumbent_site = _site(incumbent_F, incumbent)
        if incumbent_site is None:
            continue
        challenger_F = raw_ev["pf"][i]["F"]
        challenger_site = _site(challenger_F, proposed)
        absolute_win = score >= incumbent_site[1] + 0.01
        relative_win = (challenger_site is not None and
                        incumbent_site[0] >= challenger_site[0] + 2 and
                        float(incumbent_F[0, 0] - incumbent_site[1]) >=
                        float(challenger_F[0, 0] - score) + 0.008)
        if not (absolute_win or relative_win):
            continue
        incumbent_ann = ring(incumbent_index, incumbent_F, incumbent_site[0])
        if ann < incumbent_ann - 0.2:
            continue
        old_key = field(incumbent_index)
        output[old_key] = "-1"
        output[key] = raw[key]
        changed.extend((
            {"patch": old_key, "action": "release_star", "old": base[old_key], "new": "-1"},
            {"patch": key, "action": "claim_star", "old": base[key], "new": raw[key]},
        ))
    return output, changed


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", type=Path, required=True)
    parser.add_argument("--split", choices=("train", "validation"), required=True)
    parser.add_argument("--base", type=Path, required=True)
    parser.add_argument("--raw", type=Path, required=True)
    parser.add_argument("--cache", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args(argv)
    expected_fields, schema = read_rows(args.data / ("train_ground_truth.csv" if args.split == "train"
                                                       else "sample_submission.csv"))
    base_fields, base_rows = read_rows(args.base)
    raw_fields, raw_rows = read_rows(args.raw)
    if base_fields != expected_fields or raw_fields != expected_fields:
        raise ValueError("Input CSV headers differ from the competition template")
    if [row["Id"] for row in base_rows] != [row["Id"] for row in schema] or \
            [row["Id"] for row in raw_rows] != [row["Id"] for row in schema]:
        raise ValueError("Both input CSVs must have all scenes in template order")
    scenes = {scene.scene_id: scene for scene in discover_scenes(args.data / args.split)}
    predictions = []
    changes = {}
    sizes = {}
    for base, raw in zip(base_rows, raw_rows):
        scene_id = base["Id"]
        scene = scenes[scene_id]
        folder = scene.image_path.parent
        image, patches = engine.load_scene(str(folder))
        sizes[scene_id] = (image.shape[1], image.shape[0])
        evidence = engine.run_scene(str(folder), str(args.cache))
        augmented = engine.run_aug(str(folder), evidence, str(args.cache))
        equal_ev = engine.dedupe_pairs(engine.make_ev5(evidence, augmented, image))
        raw_ev = engine.dedupe_pairs(engine.make_ev5(evidence, augmented, image, w=RAW_WEIGHTS))
        prediction, scene_changes = fuse_row(base, raw, equal_ev, raw_ev, image, patches)
        predictions.append(prediction)
        if scene_changes:
            changes[scene_id] = scene_changes
        print(f"[{scene_id}] {len(scene_changes)} changed patch cells", flush=True)
    names = {path.stem.removesuffix("_pattern") for path in (args.data / "patterns").glob("*_pattern.png")}
    validate_robust_predictions(expected_fields, predictions, expected_fields, schema, names, sizes)
    args.output.mkdir(parents=True, exist_ok=True)
    destination = args.output / ("train-predictions.csv" if args.split == "train" else "submission.csv")
    write_rows(destination, expected_fields, predictions)
    report = {"split": args.split, "output": str(destination.resolve()), "scenes": len(predictions),
              "patches": sum(int(row["n_patches"]) for row in predictions), "changes": changes}
    if args.split == "train":
        truth = {row["Id"]: row for row in schema}
        report["scores"] = {row["Id"]: score_scene(truth[row["Id"]], row) for row in predictions}
        report["mean_score"] = sum(item["score"] for item in report["scores"].values()) / len(predictions)
    (args.output / "fusion-report.json").write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(f"Validated fused output: {destination.resolve()}", flush=True)


if __name__ == "__main__":
    main()
